### PR TITLE
Code Review

### PR DESCRIPTION
**Pull request by maaxayotte**
list of changes (so far): 
- we need the dummy text / comments to be straight foward
- button: is there a way we can color the icon based on the color of the button - right now it just puts a space
- button: icon needs to be right justified not based on text length
- text input error: should be underneath
- text size: check if we’ve upped the font size
- i think we should break the components out of the stories dir 🙏

"- button: is there a way we can color the icon based on the color of the button - right now it just puts a space"
This can potentially be don with a plug-in, but the SVG base functionality with Next/Image doesn't support coloring the SVG.
Might require some deliberation as to whether we want to add a dependency or have two colors for every icon (black and white).

### CODE REVIEW

**Review by fiigmnt — APPROVED** [review]

**Comment by fiigmnt** [comment]
@maaxayotte I found this to switch svg's to black:
`style={!secondary ? {filter: "invert(1)"} : {}}`
it's funky, but it works. we just need to figure out how to ignore if the svg is green + replace the spinner. let's come back to this on wednesday

**Comment by fiigmnt** [comment]
@maaxayotte I'm also seeing an issue with the `x` image on button component, could you look at that?

**Review by fiigmnt — CHANGES_REQUESTED** [review]
comments left on PR

**Comment by maaxayotte** [comment]
Updated PR based on comments !

**Review by fiigmnt — APPROVED** [review]

**Pull request merged**
